# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bwenv < Formula
  desc "CLI tool to manage .env files with Bitwarden"
  homepage "https://github.com/b4m-oss/bwenv"
  version "0.5.5"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/b4m-oss/bwenv/releases/download/v0.5.5/bwenv_darwin_amd64.tar.gz"
    sha256 "4c6739f9ed37a6a945e00682290569fb7a20878aa8980f04aa014d00b0d7ea4a"

    def install
      bin.install "bwenv"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/b4m-oss/bwenv/releases/download/v0.5.5/bwenv_darwin_arm64.tar.gz"
    sha256 "239aefff57d5359313322dcc692e51c8602c0ce95019bbd67911ed923ccc0c5e"

    def install
      bin.install "bwenv"
    end
  end

  test do
    system "#{bin}/bwenv", "--help"
  end
end
