# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-homebrew-versioned-formulas.py — DO NOT EDIT.
class BwsfAT0111 < Formula
  desc "CLI tool to manage .env files with Bitwarden"
  homepage "https://github.com/b4m-oss/bwsf"
  version "0.11.1"
  license "MIT"
  keg_only :versioned_formula

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/b4moss/bwsf/releases/download/v0.11.1/bwsf_darwin_amd64.tar.gz"
      sha256 "02d785e15e04d56830aa09746a62948784ffee4c97954044ef2f0d691f128b0c"

      define_method(:install) do
        bin.install "bwsf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/b4moss/bwsf/releases/download/v0.11.1/bwsf_darwin_arm64.tar.gz"
      sha256 "5810bdb3b41268c9eefbbeecb76c42cffbd1078af06c7c33e4fe1ed70e13820e"

      define_method(:install) do
        bin.install "bwsf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4moss/bwsf/releases/download/v0.11.1/bwsf_linux_amd64.tar.gz"
      sha256 "ef07cc875e5d062ea1b551c68535d2c71e2415b2845f271c2286c71a1c1e775f"
      define_method(:install) do
        bin.install "bwsf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4moss/bwsf/releases/download/v0.11.1/bwsf_linux_arm64.tar.gz"
      sha256 "2869f0766515705f921de6a83b6ae9953b656b413431d04d69dc54aedc5c443c"
      define_method(:install) do
        bin.install "bwsf"
      end
    end
  end

  test do
    system "#{bin}/bwsf", "--help"
  end
end
