# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BwsfAT0180 < Formula
  desc "CLI tool to manage .env files with Bitwarden"
  homepage "https://github.com/b4moss/bwsf"
  version "0.18.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/b4moss/bwsf/releases/download/v0.18.0/bwsf_darwin_amd64.tar.gz"
      sha256 "7452a28f47405e97c08fed2a3f2a7a72aab6ccba0eca46319999caa1860e3758"

      define_method(:install) do
        bin.install "bwsf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/b4moss/bwsf/releases/download/v0.18.0/bwsf_darwin_arm64.tar.gz"
      sha256 "fb9eb55d28ef5c71e49f2b88b688e31e5c970a02781c3f205cce73cc26f1faaa"

      define_method(:install) do
        bin.install "bwsf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4moss/bwsf/releases/download/v0.18.0/bwsf_linux_amd64.tar.gz"
      sha256 "967b94078d7f6ba946514365587ed6f62be55a7e1e46bb7084e5e601ab624979"
      define_method(:install) do
        bin.install "bwsf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4moss/bwsf/releases/download/v0.18.0/bwsf_linux_arm64.tar.gz"
      sha256 "51b8bbf38c562e3a2126672e4be0b578f1b4657e4a967ddf535b46a4821d9844"
      define_method(:install) do
        bin.install "bwsf"
      end
    end
  end

  keg_only :versioned_formula

  test do
    system "#{bin}/bwsf", "--help"
  end
end
