# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BwsfAT0170 < Formula
  desc "CLI tool to manage .env files with Bitwarden"
  homepage "https://github.com/b4m-oss/bwsf"
  version "0.17.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/b4moss/bwsf/releases/download/v0.17.0/bwsf_darwin_amd64.tar.gz"
      sha256 "24f92c55baa3f7633e0820a32469011b9903af4a5ca0f777b53853cde6a1a1bf"

      define_method(:install) do
        bin.install "bwsf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/b4moss/bwsf/releases/download/v0.17.0/bwsf_darwin_arm64.tar.gz"
      sha256 "efc0815caf8b191f7eb0bb3dacc7beba45bb31a876b5eab9800c8f534b2ddb7d"

      define_method(:install) do
        bin.install "bwsf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4moss/bwsf/releases/download/v0.17.0/bwsf_linux_amd64.tar.gz"
      sha256 "dc7d4d9c99fe26a76074c64b0da3c26d2295220b70e24efdd8c36200b3e54f9d"
      define_method(:install) do
        bin.install "bwsf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4moss/bwsf/releases/download/v0.17.0/bwsf_linux_arm64.tar.gz"
      sha256 "122ddcd453d94f22157261d2792c9f64065d1bef41c6c8d13190a56302b6ba29"
      define_method(:install) do
        bin.install "bwsf"
      end
    end
  end

  keg_only :versioned_formula

  test do
    system "#{bin}/bwsf", "--help"
  end
end
