# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-homebrew-versioned-formulas.py — DO NOT EDIT.
class BwsfAT0112 < Formula
  desc "CLI tool to manage .env files with Bitwarden"
  homepage "https://github.com/b4m-oss/bwsf"
  version "0.11.2"
  license "MIT"
  keg_only :versioned_formula

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/b4moss/bwsf/releases/download/v0.11.2/bwsf_darwin_amd64.tar.gz"
      sha256 "a011c4769931491dd649672bce1a8fb09230051b586e4301a292cf39907a477f"

      define_method(:install) do
        bin.install "bwsf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/b4moss/bwsf/releases/download/v0.11.2/bwsf_darwin_arm64.tar.gz"
      sha256 "8f8aeb22b547c9e78d54c115944ea53a228a46b212481eb8059fadd0fec219e0"

      define_method(:install) do
        bin.install "bwsf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4moss/bwsf/releases/download/v0.11.2/bwsf_linux_amd64.tar.gz"
      sha256 "523b99005bb4c179b70c3abfc7c1568ddd02337ba5fc75334dab002234e0228e"
      define_method(:install) do
        bin.install "bwsf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4moss/bwsf/releases/download/v0.11.2/bwsf_linux_arm64.tar.gz"
      sha256 "defa29032d5e84e6a7fba58b08799663371090349af7ddd80e4eb0404428dc5d"
      define_method(:install) do
        bin.install "bwsf"
      end
    end
  end

  test do
    system "#{bin}/bwsf", "--help"
  end
end
