# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-homebrew-versioned-formulas.py — DO NOT EDIT.
class BwsfAT080 < Formula
  desc "CLI tool to manage .env files with Bitwarden"
  homepage "https://github.com/b4m-oss/bwsf"
  version "0.8.0"
  license "MIT"
  keg_only :versioned_formula

  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/b4moss/bwsf/releases/download/v0.8.0/bwenv_darwin_amd64.tar.gz"
    sha256 "81f3a215c7d45c50ae76f3a8180b733567a6b1e94a61288d8d394828db671efe"

    define_method(:install) do
      bin.install "bwenv" => "bwsf"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/b4moss/bwsf/releases/download/v0.8.0/bwenv_darwin_arm64.tar.gz"
    sha256 "65776a3c5069a0a56e0c0acfacfbf1b7e80cede39e84be8ec4a6b0826f6f4e94"

    define_method(:install) do
      bin.install "bwenv" => "bwsf"
    end
  end

  test do
    system "#{bin}/bwsf", "--help"
  end
end
