# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bwsf < Formula
  desc "CLI tool to manage .env files with Bitwarden"
  homepage "https://github.com/b4m-oss/bwsf"
  version "0.20.0-doc.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/b4m-oss/bwsf/releases/download/v0.20.0-doc.1/bwsf_darwin_amd64.tar.gz"
      sha256 "bc02f6252c591b032ed0e0b22348e50738d3f725204f20d5d73538291d19ac99"

      define_method(:install) do
        bin.install "bwsf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/b4m-oss/bwsf/releases/download/v0.20.0-doc.1/bwsf_darwin_arm64.tar.gz"
      sha256 "3cb7a1eafd7c2256a6baa98bc6fe22c45f15acf5d172389cfc98e20a84586535"

      define_method(:install) do
        bin.install "bwsf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4m-oss/bwsf/releases/download/v0.20.0-doc.1/bwsf_linux_amd64.tar.gz"
      sha256 "4fed21ab0f81d8a30bea7b39f177c0827b4cdfe1a57e80902330d9c668f08efd"
      define_method(:install) do
        bin.install "bwsf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4m-oss/bwsf/releases/download/v0.20.0-doc.1/bwsf_linux_arm64.tar.gz"
      sha256 "cf1ac3c25c2a779f82116e323bc4eeb6c5a2917a6c0a49814aac43c64d17f256"
      define_method(:install) do
        bin.install "bwsf"
      end
    end
  end

  test do
    system "#{bin}/bwsf", "--help"
  end
end
