# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bwsf < Formula
  desc "CLI tool to manage .env files with Bitwarden"
  homepage "https://github.com/b4m-oss/bwsf"
  version "0.12.0-rc.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/b4m-oss/bwsf/releases/download/v0.12.0-rc.1/bwsf_darwin_amd64.tar.gz"
      sha256 "232d959bdddf82d04334583f30fe7cbec27eecd60fcd12029597707917e946d9"

      define_method(:install) do
        bin.install "bwsf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/b4m-oss/bwsf/releases/download/v0.12.0-rc.1/bwsf_darwin_arm64.tar.gz"
      sha256 "1f7b37cfa902a7547dc5b8890093e6eba3103dcef2f215cd050a4fc4b1455103"

      define_method(:install) do
        bin.install "bwsf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4m-oss/bwsf/releases/download/v0.12.0-rc.1/bwsf_linux_amd64.tar.gz"
      sha256 "803012cf90f7af8bdfc604229de98140c158c61d4eb4536e0e71b16f04dedc6a"
      define_method(:install) do
        bin.install "bwsf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4m-oss/bwsf/releases/download/v0.12.0-rc.1/bwsf_linux_arm64.tar.gz"
      sha256 "10329c3efee8fc1e7d2d0d7291fa3c8d186a5da902a30cf5305c9af18cc6a381"
      define_method(:install) do
        bin.install "bwsf"
      end
    end
  end

  test do
    system "#{bin}/bwsf", "--help"
  end
end
