# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-homebrew-versioned-formulas.py — DO NOT EDIT.
class BwsfAT0101 < Formula
  desc "CLI tool to manage .env files with Bitwarden"
  homepage "https://github.com/b4m-oss/bwsf"
  version "0.10.1"
  license "MIT"
  keg_only :versioned_formula

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/b4moss/bwsf/releases/download/v0.10.1/bwenv_darwin_amd64.tar.gz"
      sha256 "5d2f4e56514b810b3353e8a1c25d7f3868427bd83136c9e9bf23c40d45795e9b"

      define_method(:install) do
        bin.install "bwenv" => "bwsf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/b4moss/bwsf/releases/download/v0.10.1/bwenv_darwin_arm64.tar.gz"
      sha256 "8254f03f67aa76f42b4674984f5fc7cb52c5329bcf57c349f4ba7fc498ae41e6"

      define_method(:install) do
        bin.install "bwenv" => "bwsf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4moss/bwsf/releases/download/v0.10.1/bwenv_linux_amd64.tar.gz"
      sha256 "a1fe269cbb9399834f43f26578d09cb0d2d0fe0431576dee1a87fc096db5d558"
      define_method(:install) do
        bin.install "bwenv" => "bwsf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4moss/bwsf/releases/download/v0.10.1/bwenv_linux_arm64.tar.gz"
      sha256 "b06db13f405cf03b0702f328002e1f4eef31705766b970a7a9ccf2cdeaeea583"
      define_method(:install) do
        bin.install "bwenv" => "bwsf"
      end
    end
  end

  test do
    system "#{bin}/bwsf", "--help"
  end
end
