# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-homebrew-versioned-formulas.py — DO NOT EDIT.
class BwsfAT055 < Formula
  desc "CLI tool to manage .env files with Bitwarden"
  homepage "https://github.com/b4m-oss/bwsf"
  version "0.5.5"
  license "MIT"
  keg_only :versioned_formula

  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/b4moss/bwsf/releases/download/v0.5.5/bwenv_darwin_amd64.tar.gz"
    sha256 "4c6739f9ed37a6a945e00682290569fb7a20878aa8980f04aa014d00b0d7ea4a"

    define_method(:install) do
      bin.install "bwenv" => "bwsf"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/b4moss/bwsf/releases/download/v0.5.5/bwenv_darwin_arm64.tar.gz"
    sha256 "239aefff57d5359313322dcc692e51c8602c0ce95019bbd67911ed923ccc0c5e"

    define_method(:install) do
      bin.install "bwenv" => "bwsf"
    end
  end

  test do
    system "#{bin}/bwsf", "--help"
  end
end
