# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-homebrew-versioned-formulas.py — DO NOT EDIT.
class BwsfAT070 < Formula
  desc "CLI tool to manage .env files with Bitwarden"
  homepage "https://github.com/b4m-oss/bwsf"
  version "0.7.0"
  license "MIT"
  keg_only :versioned_formula

  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/b4moss/bwsf/releases/download/v0.7.0/bwenv_darwin_amd64.tar.gz"
    sha256 "29cc7a7751eb29adb8771880bd8c9be6a4d81a1f7a00faa7e9a6cc343e618ead"

    define_method(:install) do
      bin.install "bwenv" => "bwsf"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/b4moss/bwsf/releases/download/v0.7.0/bwenv_darwin_arm64.tar.gz"
    sha256 "6947b3c0b1ab08de41d1315a4c598b3244b61a6d7641ab0adc53ea97d08e484f"

    define_method(:install) do
      bin.install "bwenv" => "bwsf"
    end
  end

  test do
    system "#{bin}/bwsf", "--help"
  end
end
