# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BwsfAT0200 < Formula
  desc "CLI tool to manage .env files with Bitwarden"
  homepage "https://github.com/b4moss/bwsf"
  version "0.20.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/b4moss/bwsf/releases/download/v0.20.0/bwsf_darwin_amd64.tar.gz"
      sha256 "04d13ed601e7f8fbc0860d9d435745fda9de4989e80c29a395ac5b997528bb4c"

      define_method(:install) do
        bin.install "bwsf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/b4moss/bwsf/releases/download/v0.20.0/bwsf_darwin_arm64.tar.gz"
      sha256 "6127d98f35ca2f5e7f15235d2fc542113741d01d817b998db0c1d9accdcd2433"

      define_method(:install) do
        bin.install "bwsf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4moss/bwsf/releases/download/v0.20.0/bwsf_linux_amd64.tar.gz"
      sha256 "267e0cabc45cc5050e33ccfcad6c6b7c2a624658d7faa2863328f35f87a78089"
      define_method(:install) do
        bin.install "bwsf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4moss/bwsf/releases/download/v0.20.0/bwsf_linux_arm64.tar.gz"
      sha256 "4034b770668fb45ad271b7b1894b1ce223a43a6e8cd0c66ee74625f01721de75"
      define_method(:install) do
        bin.install "bwsf"
      end
    end
  end

  keg_only :versioned_formula

  test do
    system "#{bin}/bwsf", "--help"
  end
end
