# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-homebrew-versioned-formulas.py — DO NOT EDIT.
class BwsfAT0113Rc1 < Formula
  desc "CLI tool to manage .env files with Bitwarden"
  homepage "https://github.com/b4m-oss/bwsf"
  version "0.11.3-rc.1"
  license "MIT"
  keg_only :versioned_formula

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/b4moss/bwsf/releases/download/v0.11.3-rc.1/bwsf_darwin_amd64.tar.gz"
      sha256 "8cb44f21bfbb7fe44b948d2c9fadc9d502afcbb75ffdd05e61737af7efc80e95"

      define_method(:install) do
        bin.install "bwsf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/b4moss/bwsf/releases/download/v0.11.3-rc.1/bwsf_darwin_arm64.tar.gz"
      sha256 "dd6ebb8b97de81dd9b327730996071da13bfdb8c05f1ed154b85b2d71c38b1a4"

      define_method(:install) do
        bin.install "bwsf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4moss/bwsf/releases/download/v0.11.3-rc.1/bwsf_linux_amd64.tar.gz"
      sha256 "2df94a69e465716817fe7b2b323a6fd1ae9ec4a5af0b25dd2060163e6c0013cf"
      define_method(:install) do
        bin.install "bwsf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4moss/bwsf/releases/download/v0.11.3-rc.1/bwsf_linux_arm64.tar.gz"
      sha256 "ff34c573e635d21bdcd6a1822199011661cc8fa690690e0bcee05bf688c30db4"
      define_method(:install) do
        bin.install "bwsf"
      end
    end
  end

  test do
    system "#{bin}/bwsf", "--help"
  end
end
