# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-homebrew-versioned-formulas.py — DO NOT EDIT.
class BwsfAT090 < Formula
  desc "CLI tool to manage .env files with Bitwarden"
  homepage "https://github.com/b4m-oss/bwsf"
  version "0.9.0"
  license "MIT"
  keg_only :versioned_formula

  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/b4moss/bwsf/releases/download/v0.9.0/bwenv_darwin_amd64.tar.gz"
    sha256 "d53cb4fde6577d2d54e2d1cdefbc7cbd4b51ad7f124b5c061dd1e5cca2e9b12c"

    define_method(:install) do
      bin.install "bwenv" => "bwsf"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/b4moss/bwsf/releases/download/v0.9.0/bwenv_darwin_arm64.tar.gz"
    sha256 "3a77fe276f31acde38230ecb9a50bdcd58e8530273951da9db1bc256ca0b45b1"

    define_method(:install) do
      bin.install "bwenv" => "bwsf"
    end
  end

  test do
    system "#{bin}/bwsf", "--help"
  end
end
