# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-homebrew-versioned-formulas.py — DO NOT EDIT.
class BwsfAT091 < Formula
  desc "CLI tool to manage .env files with Bitwarden"
  homepage "https://github.com/b4m-oss/bwsf"
  version "0.9.1"
  license "MIT"
  keg_only :versioned_formula

  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/b4moss/bwsf/releases/download/v0.9.1/bwenv_darwin_amd64.tar.gz"
    sha256 "5ac4a7f70a4d8447458f72a9360dbd47e938858fa64efc8672ae32bb4a2f8646"

    define_method(:install) do
      bin.install "bwenv" => "bwsf"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/b4moss/bwsf/releases/download/v0.9.1/bwenv_darwin_arm64.tar.gz"
    sha256 "7519177387e8f9207c1ed25cbdc4c26afeadda16b6a12598e403c6cbd66d4e17"

    define_method(:install) do
      bin.install "bwenv" => "bwsf"
    end
  end

  test do
    system "#{bin}/bwsf", "--help"
  end
end
