# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-homebrew-versioned-formulas.py — DO NOT EDIT.
class BwsfAT0110 < Formula
  desc "CLI tool to manage .env files with Bitwarden"
  homepage "https://github.com/b4m-oss/bwsf"
  version "0.11.0"
  license "MIT"
  keg_only :versioned_formula

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/b4moss/bwsf/releases/download/v0.11.0/bwenv_darwin_amd64.tar.gz"
      sha256 "d58893bb399ae83b818bc6a4d3123739cbe5bbab096db5d354012d6c3927ec69"

      define_method(:install) do
        bin.install "bwenv" => "bwsf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/b4moss/bwsf/releases/download/v0.11.0/bwenv_darwin_arm64.tar.gz"
      sha256 "168a66480768f395404b7b1523adf1f1a38aef6aa7174dfd4a8387f7026a57e8"

      define_method(:install) do
        bin.install "bwenv" => "bwsf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4moss/bwsf/releases/download/v0.11.0/bwenv_linux_amd64.tar.gz"
      sha256 "0bd4908c829e7627bbbeb4fbeca99cc42d21fcb8aa7cac852dddb22abf944e67"
      define_method(:install) do
        bin.install "bwenv" => "bwsf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4moss/bwsf/releases/download/v0.11.0/bwenv_linux_arm64.tar.gz"
      sha256 "adf16f6e51cf47bdcab01e7b001b823d94c7b1243ce0faccde0fe1d3ebb6dec4"
      define_method(:install) do
        bin.install "bwenv" => "bwsf"
      end
    end
  end

  test do
    system "#{bin}/bwsf", "--help"
  end
end
