# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-homebrew-versioned-formulas.py — DO NOT EDIT.
class BwsfAT060 < Formula
  desc "CLI tool to manage .env files with Bitwarden"
  homepage "https://github.com/b4m-oss/bwsf"
  version "0.6.0"
  license "MIT"
  keg_only :versioned_formula

  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/b4moss/bwsf/releases/download/v0.6.0/bwenv_darwin_amd64.tar.gz"
    sha256 "07d89539303bbe31329146e68ef2a3d5b0eefa780163de0fb7d32339861cbe26"

    define_method(:install) do
      bin.install "bwenv" => "bwsf"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/b4moss/bwsf/releases/download/v0.6.0/bwenv_darwin_arm64.tar.gz"
    sha256 "ddedaf96557d612271ba0e9ae6aed99ca9dcf6d305fb4ec15fbc374eecd3c4dc"

    define_method(:install) do
      bin.install "bwenv" => "bwsf"
    end
  end

  test do
    system "#{bin}/bwsf", "--help"
  end
end
