# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-homebrew-versioned-formulas.py — DO NOT EDIT.
class BwsfAT0130 < Formula
  desc "CLI tool to manage .env files with Bitwarden"
  homepage "https://github.com/b4m-oss/bwsf"
  version "0.13.0"
  license "MIT"
  keg_only :versioned_formula

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/b4moss/bwsf/releases/download/v0.13.0/bwsf_darwin_amd64.tar.gz"
      sha256 "3795b15e472b4af62951f5dae0ff1e51f6bb839630b2281ba2e5c717f73a612d"

      define_method(:install) do
        bin.install "bwsf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/b4moss/bwsf/releases/download/v0.13.0/bwsf_darwin_arm64.tar.gz"
      sha256 "70099a1b31ed1766dbaf3c80f3f52aa1b234eefa6a3a0bee90abf84a1f9db6a9"

      define_method(:install) do
        bin.install "bwsf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4moss/bwsf/releases/download/v0.13.0/bwsf_linux_amd64.tar.gz"
      sha256 "dbf6459c35d7b3c6a51f51ced2f156d52194b4728b65f42184c4e02cb7c26ce6"
      define_method(:install) do
        bin.install "bwsf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4moss/bwsf/releases/download/v0.13.0/bwsf_linux_arm64.tar.gz"
      sha256 "eab563c1703833661d7230ae603b62b1f5d0a0ad288c2159c58609176ec22578"
      define_method(:install) do
        bin.install "bwsf"
      end
    end
  end

  test do
    system "#{bin}/bwsf", "--help"
  end
end
