# typed: false
# frozen_string_literal: true

# Generated by scripts/sync-homebrew-versioned-formulas.py — DO NOT EDIT.
class BwsfAT0120 < Formula
  desc "CLI tool to manage .env files with Bitwarden"
  homepage "https://github.com/b4m-oss/bwsf"
  version "0.12.0"
  license "MIT"
  keg_only :versioned_formula

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/b4moss/bwsf/releases/download/v0.12.0/bwsf_darwin_amd64.tar.gz"
      sha256 "b562fd590b5193d924b72555d57d346484608bf2b20432fbfb7d5d21b0f49bc7"

      define_method(:install) do
        bin.install "bwsf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/b4moss/bwsf/releases/download/v0.12.0/bwsf_darwin_arm64.tar.gz"
      sha256 "9e01a14ad4dfa575fd8134c6dbc04f9fdd59b0d5d13dcfdfc43cc29b836278c0"

      define_method(:install) do
        bin.install "bwsf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4moss/bwsf/releases/download/v0.12.0/bwsf_linux_amd64.tar.gz"
      sha256 "5a02c2ca0d4c39d4210293cdcbb380a45bc795a805ff1931279a8f38ddeed299"
      define_method(:install) do
        bin.install "bwsf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/b4moss/bwsf/releases/download/v0.12.0/bwsf_linux_arm64.tar.gz"
      sha256 "70c3af2c3001690c137df85c698be0cc5d3f41d9a251fd019bf2e027d872db34"
      define_method(:install) do
        bin.install "bwsf"
      end
    end
  end

  test do
    system "#{bin}/bwsf", "--help"
  end
end
